export const UPDATE_PANEL = 'UPDATE_PANEL';
export const UPDATE_ELEMENT = 'UPDATE_ELEMENT';
export const CREATE_ELEMENT = 'CREATE_ELEMENT';
export const REMOVE_ELEMENT = 'REMOVE_ELEMENT';
export const SELECT_ELEMENT = 'SELECT_ELEMENT';
